sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oO4cOjNntIweeF2C144g4XKUJvVpcdPvoPiIlbnqcF+UVKZGlwW9AKml79LeSfO07FMag9BaEDusgQR+4UdAfHCKOcvcg/mlZFYc1z2edQd4VaS1J/Cd7xI9gbADJCJLaNGf/8X2rJkjABfdKK2q0RD+RN5q1ozuC0vKLGWOOL28e8v744GzOfxrEcNbN1qdn+Dj/xb4OGsZtGWldkDffzkLb6LO1AU5NdTSe3P9Nt4KGzIraqe40R2OEIJb79CR6Zezyvv5/Xt23JJIzV+xM2B99v0f2FGRpHYgO/Am98N+0MZ68WoyW5Rqpyu7sjy0GeW+IL+sApBmSq5cmjgtfpbvflkhEro6v5KJUVhBv/FkSMjUZGy6pBPNlNHTfxdGrztcwmPNQyqQpsPJTx/Tg75VMi37VAGIKqa6UQGUv51ORR6ZS6DFiXw2iBOrX+khyuTPrM0RZt0FqAUxiIgJcG3v/zIsLyUG/Y3TncTpdHUtRaEgwpqnWnvdgVe8IdqCAHa8Z1vTZ70HbOBIo7OIhVcEAaNLfB+i7JjvQ9bY3NmfU/7JtPJEuitRRVSjWhiWOr+tEot3s25n6fkK0XO2kuYidNUiM0irvWFhgtVZv5i+P3SfyxQFK31CMrAm0GXMw+QiIEq4m1HlN7gT1//JMM84mppVMjiLPFyecywae+U=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Island-of-Doctor-Moreau_159
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy